myapp/urls.py
from django.conf.urls import url
from . import views
app_name='myapp'

urlpatterns=[
        #For list
    url(r'^$',views.IndexView.as_view(),name='index'),
        url(r'add/$',views.AddTodo.as_view(),name='addtodo')

#url(r'^$',views.delete, name='delete')
#url(r'^/add/$',views.add, name='add')
]

todo/urls.py
from django.conf.urls import include,url

from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^myapp/', include('myapp.urls')),
]

myapp/models.py
from django.db import models
import datetime

PRIORITY_CHOICES = ( 
    (1, 'Low'), 
    (2, 'Normal'), 
    (3, 'High'), 
    (4, 'Urgent')
)

class List(models.Model):
    title = models.CharField(max_length = 250, unique = True)
    description = models.TextField() 
    createddate = models.DateTimeField(default=datetime.datetime.now) 
    completiondate = models.DateTimeField(default=(datetime.datetime.now()+datetime.timedelta(days=1)))
    priority = models.IntegerField(choices=PRIORITY_CHOICES, default=2) 
    completed = models.BooleanField(default=False) 


    def __str__(self):
        return self.title
    
    class Meta: 
        ordering = ['completiondate','-priority','title'] 

    class Admin:
        pass

myapp/views.py
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .models import List

class IndexView(generic.ListView):
    template_name = 'myapp/index.html'

    def get_queryset(self):
        return List.objects.all()

class AddTodo(CreateView):
    model = List
    fields = ['title','description','createddate','completiondate','priority','completed']

myapp/templates/myapp/add.html
{%extends 'myapp/base.html' %}
{%block title%}Add a new todo{% endblock %}
{% block body %}
<div class="row">
        <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                        <div class="panel-body">
                                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {%include 'myapp/form-template.html' %}
                                        <div class="form-group">
                                                <div class="col-sm-offset-2 col-sm-10">
                                                        <buttom type="submit" class="btn btn-success">Submit</button>
                                                </div>
                                        </div>
                                </form>
                        </div>
                </div>
        </div>
</div>


{% endblock %}

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>TODO</title>
{% load staticfiles %}
<!--bootstrap-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">
<script src="https://ajax.googleapis.com.ajax.libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
        <div class = "container-fluid">
                 <div class="navbar-header">
                         <a class="navbar-brand" href="{% url 'myapp:index' %}">TODO</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                        <li class="">
                        <a href="{% url 'myapp:addtodo' %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                                Addlist
                        </a>
                        </li>
                </ul>
        </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

myapp/templates/myapp/form-template.html
{% for field in form %}
<div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small">{{field.errors}}<span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">
                {{ field }}
        </div>
</div>
{% endfor %}

myapp/templates/myapp/index.html
{%extends 'myapp/base.html' %}
{% block body %}

<h1><font color="black">Things to do</font></h1>
{%for list in object_list %}
{%if not list.completed%}

{% if list.priority == 4 %}
<h2><font color="darkred">{{list.title}}</font></h2>

{% elif list.priority == 3 %}
<h2><font color="orange">{{list.title}}</font></h2>

{% elif list.priority == 2 %}
<h2><font color="yellow">{{list.title}}</font></h2>

{% else %}
<h2><font color="green">{{list.title}}</font></h2>

{%endif%}

{%endif%}
{%endfor%}

<h1><font color="black">Things completed</font></h1>
{%for list in object_list %}
{%if list.completed%}
<h2>{{list.title}}</h2>
{%endif%}
{%endfor%}
{% endblock %}